package uk.gibby.neo4k.paths

import uk.gibby.neo4k.core.*
import uk.gibby.neo4k.returns.ReturnValue
import uk.gibby.neo4k.returns.empty.EmptyReturn
import uk.gibby.neo4k.returns.graph.entities.DirectionalRelationship
import uk.gibby.neo4k.returns.graph.entities.Node
import uk.gibby.neo4k.returns.graph.entities.NonDirectionalRelationship
import uk.gibby.neo4k.returns.graph.entities.Relationship
import uk.gibby.neo4k.returns.util.NodeReference
import kotlin.reflect.KFunction


data class NeoPath8<A : ReturnValue<*>, B : ReturnValue<*>, C : ReturnValue<*>, D : ReturnValue<*>, E : ReturnValue<*>, F : ReturnValue<*>, G : ReturnValue<*>, H : ReturnValue<*>, I : ReturnValue<*>, J : ReturnValue<*>, K : ReturnValue<*>, L : ReturnValue<*>, M : ReturnValue<*>, N : ReturnValue<*>, O : ReturnValue<*>>(
    val first: A,
    val firstToSecond: B,
    val second: C,
    val secondToThird: D,
    val third: E,
    val thirdToFourth: F,
    val fourth: G,
    val fourthToFifth: H,
    val fifth: I,
    val fifthToSixth: J,
    val sixth: K,
    val sixthToSeventh: L,
    val seventh: M,
    val seventhToEighth: N,
    val eighth: O,
    val ref: String
) : EmptyReturn()

class NeoMatchablePath8<A : Node<*>, B : Relationship<*, *, *>, C : Node<*>, D : Relationship<*, *, *>, E : Node<*>, F : Relationship<*, *, *>, G : Node<*>, H : Relationship<*, *, *>, I : Node<*>, J : Relationship<*, *, *>, K : Node<*>, L : Relationship<*, *, *>, M : Node<*>, N : Relationship<*, *, *>, O : Node<*>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val seventhToEighthDir: PathDirection,
    val eighth: Searchable<O>,
    override val ref: String
) : Matchable<NeoPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>>,
    Creatable<NeoPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>> {
    override fun getCreateString() =
        "${first.getCreateString()}${if (firstToSecondDir == PathDirection.Backwards) "<-" else "-"}${firstToSecond.getMatchString()}${if (firstToSecondDir != PathDirection.Backwards) "->" else "-"}${second.getCreateString()}${if (secondToThirdDir == PathDirection.Backwards) "<-" else "-"}${secondToThird.getMatchString()}${if (secondToThirdDir != PathDirection.Backwards) "->" else "-"}${third.getCreateString()}${if (thirdToFourthDir == PathDirection.Backwards) "<-" else "-"}${thirdToFourth.getMatchString()}${if (thirdToFourthDir != PathDirection.Backwards) "->" else "-"}${fourth.getCreateString()}${if (fourthToFifthDir == PathDirection.Backwards) "<-" else "-"}${fourthToFifth.getMatchString()}${if (fourthToFifthDir != PathDirection.Backwards) "->" else "-"}${fifth.getCreateString()}${if (fifthToSixthDir == PathDirection.Backwards) "<-" else "-"}${fifthToSixth.getMatchString()}${if (fifthToSixthDir != PathDirection.Backwards) "->" else "-"}${sixth.getCreateString()}${if (sixthToSeventhDir == PathDirection.Backwards) "<-" else "-"}${sixthToSeventh.getMatchString()}${if (sixthToSeventhDir != PathDirection.Backwards) "->" else "-"}${seventh.getCreateString()}${if (seventhToEighthDir == PathDirection.Backwards) "<-" else "-"}${seventhToEighth.getMatchString()}${if (seventhToEighthDir != PathDirection.Backwards) "->" else "-"}${eighth.getCreateString()}"

    override fun getMatchString() =
        "(${first.getMatchString()})${if (firstToSecondDir == PathDirection.Backwards) "<-" else "-"}${firstToSecond.getMatchString()}${if (firstToSecondDir == PathDirection.Forwards) "->" else "-"}${second.getCreateString()}${if (secondToThirdDir == PathDirection.Backwards) "<-" else "-"}${secondToThird.getMatchString()}${if (secondToThirdDir == PathDirection.Forwards) "->" else "-"}${third.getCreateString()}${if (thirdToFourthDir == PathDirection.Backwards) "<-" else "-"}${thirdToFourth.getMatchString()}${if (thirdToFourthDir == PathDirection.Forwards) "->" else "-"}${fourth.getCreateString()}${if (fourthToFifthDir == PathDirection.Backwards) "<-" else "-"}${fourthToFifth.getMatchString()}${if (fourthToFifthDir == PathDirection.Forwards) "->" else "-"}${fifth.getCreateString()}${if (fifthToSixthDir == PathDirection.Backwards) "<-" else "-"}${fifthToSixth.getMatchString()}${if (fifthToSixthDir == PathDirection.Forwards) "->" else "-"}${sixth.getCreateString()}${if (sixthToSeventhDir == PathDirection.Backwards) "<-" else "-"}${sixthToSeventh.getMatchString()}${if (sixthToSeventhDir == PathDirection.Forwards) "->" else "-"}${seventh.getCreateString()}${if (seventhToEighthDir == PathDirection.Backwards) "<-" else "-"}${seventhToEighth.getMatchString()}${if (seventhToEighthDir == PathDirection.Forwards) "->" else "-"}${eighth.getCreateString()}"

    override fun getReference() = NeoPath8(
        first.getReference(),
        firstToSecond.getReference(),
        second.getReference(),
        secondToThird.getReference(),
        third.getReference(),
        thirdToFourth.getReference(),
        fourth.getReference(),
        fourthToFifth.getReference(),
        fifth.getReference(),
        fifthToSixth.getReference(),
        sixth.getReference(),
        sixthToSeventh.getReference(),
        seventh.getReference(),
        seventhToEighth.getReference(),
        eighth.getReference(),
        ref
    )

}

class NoDirOpenPath8<A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : NonDirectionalRelationship<M, *>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val ref: String
)

class ForwardOpenPath8<A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<M, O, *>,
        O : Node<*>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val ref: String
)

class BackwardsOpenPath8<A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<O, M, *>,
        O : Node<*>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val ref: String
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<M, O, *>,
        O : Node<*>> NeoMatchablePath7<A, B, C, D, E, F, G, H, I, J, K, L, M>.`o-→`(relation: RelationParamMap<N>) =
    ForwardOpenPath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        relation,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<M, O, *>,
        O : Node<*>> NeoMatchablePath7<A, B, C, D, E, F, G, H, I, J, K, L, M>.`o-→`(relation: KFunction<N>) =
    ForwardOpenPath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        relation {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<O, M, *>,
        O : Node<*>> NeoMatchablePath7<A, B, C, D, E, F, G, H, I, J, K, L, M>.`←-o`(relation: RelationParamMap<N>) =
    BackwardsOpenPath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        relation,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<O, M, *>,
        O : Node<*>> NeoMatchablePath7<A, B, C, D, E, F, G, H, I, J, K, L, M>.`←-o`(relation: KFunction<N>) =
    BackwardsOpenPath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        relation {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : NonDirectionalRelationship<M, *>> NeoMatchablePath7<A, B, C, D, E, F, G, H, I, J, K, L, M>.`-o-`(
    relation: RelationParamMap<N>
) = NoDirOpenPath8(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    relation,
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : NonDirectionalRelationship<M, *>> NeoMatchablePath7<A, B, C, D, E, F, G, H, I, J, K, L, M>.`-o-`(
    relation: KFunction<N>
) = NoDirOpenPath8(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    relation {},
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<O, M, *>,
        O : Node<*>> BackwardsOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`←-o`(node: Searchable<O>) =
    NeoMatchablePath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        PathDirection.Backwards,
        node,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<O, M, *>,
        O : Node<*>> BackwardsOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`←-o`(node: KFunction<O>) =
    NeoMatchablePath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        PathDirection.Backwards,
        node {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<O, M, *>,
        O : Node<*>> BackwardsOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`←-o`(node: O) = NeoMatchablePath8(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    PathDirection.Backwards,
    NodeReference(node),
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<M, O, *>,
        O : Node<*>> ForwardOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`o-→`(node: Searchable<O>) =
    NeoMatchablePath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        PathDirection.Forwards,
        node,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<M, O, *>,
        O : Node<*>> ForwardOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`o-→`(node: KFunction<O>) =
    NeoMatchablePath8(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        PathDirection.Forwards,
        node {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : DirectionalRelationship<M, O, *>,
        O : Node<*>> ForwardOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`o-→`(node: O) = NeoMatchablePath8(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    PathDirection.Forwards,
    NodeReference(node),
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : NonDirectionalRelationship<M, *>> NoDirOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N>.`-o-`(
    node: Searchable<M>
) = NeoMatchablePath8(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    PathDirection.None,
    node,
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : NonDirectionalRelationship<M, *>> NoDirOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N>.`-o-`(
    node: KFunction<M>
) = NeoMatchablePath8(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    PathDirection.None,
    node {},
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : NonDirectionalRelationship<M, *>> NoDirOpenPath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N>.`-o-`(
    node: M
) = NeoMatchablePath8(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    PathDirection.None,
    NodeReference(node),
    ref
)

