package uk.gibby.neo4k.paths

import uk.gibby.neo4k.core.*
import uk.gibby.neo4k.returns.ReturnValue
import uk.gibby.neo4k.returns.empty.EmptyReturn
import uk.gibby.neo4k.returns.graph.entities.DirectionalRelationship
import uk.gibby.neo4k.returns.graph.entities.Node
import uk.gibby.neo4k.returns.graph.entities.NonDirectionalRelationship
import uk.gibby.neo4k.returns.graph.entities.Relationship
import uk.gibby.neo4k.returns.util.NodeReference
import kotlin.reflect.KFunction


data class NeoPath9<A : ReturnValue<*>, B : ReturnValue<*>, C : ReturnValue<*>, D : ReturnValue<*>, E : ReturnValue<*>, F : ReturnValue<*>, G : ReturnValue<*>, H : ReturnValue<*>, I : ReturnValue<*>, J : ReturnValue<*>, K : ReturnValue<*>, L : ReturnValue<*>, M : ReturnValue<*>, N : ReturnValue<*>, O : ReturnValue<*>, P : ReturnValue<*>, Q : ReturnValue<*>>(
    val first: A,
    val firstToSecond: B,
    val second: C,
    val secondToThird: D,
    val third: E,
    val thirdToFourth: F,
    val fourth: G,
    val fourthToFifth: H,
    val fifth: I,
    val fifthToSixth: J,
    val sixth: K,
    val sixthToSeventh: L,
    val seventh: M,
    val seventhToEighth: N,
    val eighth: O,
    val eighthToNinth: P,
    val ninth: Q,
    val ref: String
) : EmptyReturn()

class NeoMatchablePath9<A : Node<*>, B : Relationship<*, *, *>, C : Node<*>, D : Relationship<*, *, *>, E : Node<*>, F : Relationship<*, *, *>, G : Node<*>, H : Relationship<*, *, *>, I : Node<*>, J : Relationship<*, *, *>, K : Node<*>, L : Relationship<*, *, *>, M : Node<*>, N : Relationship<*, *, *>, O : Node<*>, P : Relationship<*, *, *>, Q : Node<*>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val seventhToEighthDir: PathDirection,
    val eighth: Searchable<O>,
    val eighthToNinth: RelationParamMap<P>,
    val eighthToNinthDir: PathDirection,
    val ninth: Searchable<Q>,
    override val ref: String
) : Matchable<NeoPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>>,
    Creatable<NeoPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>> {
    override fun getCreateString() =
        "${first.getCreateString()}${if (firstToSecondDir == PathDirection.Backwards) "<-" else "-"}${firstToSecond.getMatchString()}${if (firstToSecondDir != PathDirection.Backwards) "->" else "-"}${second.getCreateString()}${if (secondToThirdDir == PathDirection.Backwards) "<-" else "-"}${secondToThird.getMatchString()}${if (secondToThirdDir != PathDirection.Backwards) "->" else "-"}${third.getCreateString()}${if (thirdToFourthDir == PathDirection.Backwards) "<-" else "-"}${thirdToFourth.getMatchString()}${if (thirdToFourthDir != PathDirection.Backwards) "->" else "-"}${fourth.getCreateString()}${if (fourthToFifthDir == PathDirection.Backwards) "<-" else "-"}${fourthToFifth.getMatchString()}${if (fourthToFifthDir != PathDirection.Backwards) "->" else "-"}${fifth.getCreateString()}${if (fifthToSixthDir == PathDirection.Backwards) "<-" else "-"}${fifthToSixth.getMatchString()}${if (fifthToSixthDir != PathDirection.Backwards) "->" else "-"}${sixth.getCreateString()}${if (sixthToSeventhDir == PathDirection.Backwards) "<-" else "-"}${sixthToSeventh.getMatchString()}${if (sixthToSeventhDir != PathDirection.Backwards) "->" else "-"}${seventh.getCreateString()}${if (seventhToEighthDir == PathDirection.Backwards) "<-" else "-"}${seventhToEighth.getMatchString()}${if (seventhToEighthDir != PathDirection.Backwards) "->" else "-"}${eighth.getCreateString()}${if (eighthToNinthDir == PathDirection.Backwards) "<-" else "-"}${eighthToNinth.getMatchString()}${if (eighthToNinthDir != PathDirection.Backwards) "->" else "-"}${ninth.getCreateString()}"

    override fun getMatchString() =
        "(${first.getMatchString()})${if (firstToSecondDir == PathDirection.Backwards) "<-" else "-"}${firstToSecond.getMatchString()}${if (firstToSecondDir == PathDirection.Forwards) "->" else "-"}${second.getCreateString()}${if (secondToThirdDir == PathDirection.Backwards) "<-" else "-"}${secondToThird.getMatchString()}${if (secondToThirdDir == PathDirection.Forwards) "->" else "-"}${third.getCreateString()}${if (thirdToFourthDir == PathDirection.Backwards) "<-" else "-"}${thirdToFourth.getMatchString()}${if (thirdToFourthDir == PathDirection.Forwards) "->" else "-"}${fourth.getCreateString()}${if (fourthToFifthDir == PathDirection.Backwards) "<-" else "-"}${fourthToFifth.getMatchString()}${if (fourthToFifthDir == PathDirection.Forwards) "->" else "-"}${fifth.getCreateString()}${if (fifthToSixthDir == PathDirection.Backwards) "<-" else "-"}${fifthToSixth.getMatchString()}${if (fifthToSixthDir == PathDirection.Forwards) "->" else "-"}${sixth.getCreateString()}${if (sixthToSeventhDir == PathDirection.Backwards) "<-" else "-"}${sixthToSeventh.getMatchString()}${if (sixthToSeventhDir == PathDirection.Forwards) "->" else "-"}${seventh.getCreateString()}${if (seventhToEighthDir == PathDirection.Backwards) "<-" else "-"}${seventhToEighth.getMatchString()}${if (seventhToEighthDir == PathDirection.Forwards) "->" else "-"}${eighth.getCreateString()}${if (eighthToNinthDir == PathDirection.Backwards) "<-" else "-"}${eighthToNinth.getMatchString()}${if (eighthToNinthDir == PathDirection.Forwards) "->" else "-"}${ninth.getCreateString()}"

    override fun getReference() = NeoPath9(
        first.getReference(),
        firstToSecond.getReference(),
        second.getReference(),
        secondToThird.getReference(),
        third.getReference(),
        thirdToFourth.getReference(),
        fourth.getReference(),
        fourthToFifth.getReference(),
        fifth.getReference(),
        fifthToSixth.getReference(),
        sixth.getReference(),
        sixthToSeventh.getReference(),
        seventh.getReference(),
        seventhToEighth.getReference(),
        eighth.getReference(),
        eighthToNinth.getReference(),
        ninth.getReference(),
        ref
    )

}

class NoDirOpenPath9<A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : NonDirectionalRelationship<O, *>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val seventhToEighthDir: PathDirection,
    val eighth: Searchable<O>,
    val eighthToNinth: RelationParamMap<P>,
    val ref: String
)

class ForwardOpenPath9<A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<O, Q, *>,
        Q : Node<*>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val seventhToEighthDir: PathDirection,
    val eighth: Searchable<O>,
    val eighthToNinth: RelationParamMap<P>,
    val ref: String
)

class BackwardsOpenPath9<A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<Q, O, *>,
        Q : Node<*>>(
    val first: Searchable<A>,
    val firstToSecond: RelationParamMap<B>,
    val firstToSecondDir: PathDirection,
    val second: Searchable<C>,
    val secondToThird: RelationParamMap<D>,
    val secondToThirdDir: PathDirection,
    val third: Searchable<E>,
    val thirdToFourth: RelationParamMap<F>,
    val thirdToFourthDir: PathDirection,
    val fourth: Searchable<G>,
    val fourthToFifth: RelationParamMap<H>,
    val fourthToFifthDir: PathDirection,
    val fifth: Searchable<I>,
    val fifthToSixth: RelationParamMap<J>,
    val fifthToSixthDir: PathDirection,
    val sixth: Searchable<K>,
    val sixthToSeventh: RelationParamMap<L>,
    val sixthToSeventhDir: PathDirection,
    val seventh: Searchable<M>,
    val seventhToEighth: RelationParamMap<N>,
    val seventhToEighthDir: PathDirection,
    val eighth: Searchable<O>,
    val eighthToNinth: RelationParamMap<P>,
    val ref: String
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<O, Q, *>,
        Q : Node<*>> NeoMatchablePath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`o-→`(relation: RelationParamMap<P>) =
    ForwardOpenPath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        relation,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<O, Q, *>,
        Q : Node<*>> NeoMatchablePath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`o-→`(relation: KFunction<P>) =
    ForwardOpenPath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        relation {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<Q, O, *>,
        Q : Node<*>> NeoMatchablePath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`←-o`(relation: RelationParamMap<P>) =
    BackwardsOpenPath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        relation,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<Q, O, *>,
        Q : Node<*>> NeoMatchablePath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`←-o`(relation: KFunction<P>) =
    BackwardsOpenPath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        relation {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : NonDirectionalRelationship<O, *>> NeoMatchablePath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`-o-`(
    relation: RelationParamMap<P>
) = NoDirOpenPath9(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    seventhToEighthDir,
    eighth,
    relation,
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : NonDirectionalRelationship<O, *>> NeoMatchablePath8<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>.`-o-`(
    relation: KFunction<P>
) = NoDirOpenPath9(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    seventhToEighthDir,
    eighth,
    relation {},
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<Q, O, *>,
        Q : Node<*>> BackwardsOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>.`←-o`(node: Searchable<Q>) =
    NeoMatchablePath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        eighthToNinth,
        PathDirection.Backwards,
        node,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<Q, O, *>,
        Q : Node<*>> BackwardsOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>.`←-o`(node: KFunction<Q>) =
    NeoMatchablePath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        eighthToNinth,
        PathDirection.Backwards,
        node {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<Q, O, *>,
        Q : Node<*>> BackwardsOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>.`←-o`(node: Q) =
    NeoMatchablePath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        eighthToNinth,
        PathDirection.Backwards,
        NodeReference(node),
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<O, Q, *>,
        Q : Node<*>> ForwardOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>.`o-→`(node: Searchable<Q>) =
    NeoMatchablePath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        eighthToNinth,
        PathDirection.Forwards,
        node,
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<O, Q, *>,
        Q : Node<*>> ForwardOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>.`o-→`(node: KFunction<Q>) =
    NeoMatchablePath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        eighthToNinth,
        PathDirection.Forwards,
        node {},
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : DirectionalRelationship<O, Q, *>,
        Q : Node<*>> ForwardOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>.`o-→`(node: Q) =
    NeoMatchablePath9(
        first,
        firstToSecond,
        firstToSecondDir,
        second,
        secondToThird,
        secondToThirdDir,
        third,
        thirdToFourth,
        thirdToFourthDir,
        fourth,
        fourthToFifth,
        fourthToFifthDir,
        fifth,
        fifthToSixth,
        fifthToSixthDir,
        sixth,
        sixthToSeventh,
        sixthToSeventhDir,
        seventh,
        seventhToEighth,
        seventhToEighthDir,
        eighth,
        eighthToNinth,
        PathDirection.Forwards,
        NodeReference(node),
        ref
    )

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : NonDirectionalRelationship<O, *>> NoDirOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>.`-o-`(
    node: Searchable<O>
) = NeoMatchablePath9(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    seventhToEighthDir,
    eighth,
    eighthToNinth,
    PathDirection.None,
    node,
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : NonDirectionalRelationship<O, *>> NoDirOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>.`-o-`(
    node: KFunction<O>
) = NeoMatchablePath9(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    seventhToEighthDir,
    eighth,
    eighthToNinth,
    PathDirection.None,
    node {},
    ref
)

infix fun <A : Node<*>, B : Relationship<*, *, *>,
        C : Node<*>, D : Relationship<*, *, *>,
        E : Node<*>, F : Relationship<*, *, *>,
        G : Node<*>, H : Relationship<*, *, *>,
        I : Node<*>, J : Relationship<*, *, *>,
        K : Node<*>, L : Relationship<*, *, *>,
        M : Node<*>, N : Relationship<*, *, *>,
        O : Node<*>, P : NonDirectionalRelationship<O, *>> NoDirOpenPath9<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>.`-o-`(
    node: O
) = NeoMatchablePath9(
    first,
    firstToSecond,
    firstToSecondDir,
    second,
    secondToThird,
    secondToThirdDir,
    third,
    thirdToFourth,
    thirdToFourthDir,
    fourth,
    fourthToFifth,
    fourthToFifthDir,
    fifth,
    fifthToSixth,
    fifthToSixthDir,
    sixth,
    sixthToSeventh,
    sixthToSeventhDir,
    seventh,
    seventhToEighth,
    seventhToEighthDir,
    eighth,
    eighthToNinth,
    PathDirection.None,
    NodeReference(node),
    ref
)

